version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: taskflow-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: taskflow
    volumes:
      - mongodb_data:/data/db
    networks:
      - taskflow-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskflow-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://admin:password@mongodb:27017/taskflow?authSource=admin
      JWT_SECRET: your-secret-key-here
      PORT: 5000
    depends_on:
      - mongodb
    networks:
      - taskflow-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: taskflow-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000
    depends_on:
      - server
    networks:
      - taskflow-network

  nginx:
    image: nginx:alpine
    container_name: taskflow-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - client
      - server
    networks:
      - taskflow-network

volumes:
  mongodb_data:

networks:
  taskflow-network:
    driver: bridge
